; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
boards_dir = boards

[env:waveshare_esp32-s3-touch-lcd-5b]
platform = espressif32 @ 6.6.0
board = waveshare_esp32-s3-touch-lcd-5b
framework = arduino
monitor_port = COM7
monitor_speed = 115200
upload_port = COM7
upload_speed = 115200
build_flags = 
	-D BOARD_WAVESHARE_ESP32_S3_TOUCH_LCD_5B
	-D CORE_DEBUG_LEVEL=3
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D BOARD_HAS_PSRAM
	-D LV_CONF_INCLUDE_SIMPLE
	-D CONFIG_BT_BLE_42_FEATURES_SUPPORTED=1
    -D CONFIG_BT_NIMBLE_MEM_ALLOC_MODE_EXTERNAL=1
    -D ARDUINO_RUNNING_CORE=1
    -D ARDUINO_EVENT_RUNNING_CORE=1
	-std=gnu++17
	-I include
	-I src
build_unflags = -std=gnu++11
board_build.filesystem = littlefs
board_build.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi
board_build.f_flash = 80000000L
board_build.f_cpu = 240000000L
lib_deps = 
	lvgl/lvgl @ 8.4.0
	ESP32_Display_Panel
	tamctec/TAMC_GT911@^1.0.2
	ArduinoJson
	NimBLE-Arduino